#!/usr/bin/env python3
"""Discover local Compose identities and persist reciprocal L2 configuration."""
import fcntl
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import time

ROOT = Path(__file__).resolve().parent
MARKER = '# Generated by configure_l2_proxy.py; rerun the script to refresh.\n'
KEY = re.compile(r'[0-9a-fA-F]{64}')


class SetupError(Exception):
    pass


def compose(files, *args, env=None, check=True):
    command = ['docker', 'compose', '--project-directory', str(ROOT)]
    for path in files:
        command.extend(['-f', str(path)])
    result = subprocess.run(command + list(args), cwd=ROOT, env=env,
                            capture_output=True, text=True, timeout=240)
    if check and result.returncode:
        # Config output and environment can contain RPC credentials. Keep errors
        # out of setup output; operators can inspect Compose directly if needed.
        raise SetupError('Docker Compose failed; check service configuration and docker compose logs.')
    return result


def public_key(files, name, network):
    port = 11023 if network == 'stagenet' else 22023
    result = compose(files, 'exec', '-T', name, 'curl', '--fail', '--silent',
                     '--max-time', '5', '-H', 'Content-Type: application/json',
                     '-d', '{"jsonrpc":"2.0","id":1,"method":"get_service_keys"}',
                     f'http://127.0.0.1:{port}/json_rpc', check=False)
    if result.returncode:
        return None
    try:
        response = json.loads(result.stdout)['result']
        key = response['service_node_ed25519_pubkey']
        if response.get('status') == 'OK' and isinstance(key, str) and KEY.fullmatch(key):
            return key.lower()
    except (ValueError, KeyError, TypeError):
        pass
    return None


def await_key(files, name, network):
    deadline = time.monotonic() + 120
    while time.monotonic() < deadline:
        key = public_key(files, name, network)
        if key:
            return key
        time.sleep(1)
    raise SetupError(f'Timed out reading the public key for {name}; inspect its container logs.')


def dump_override(document):
    # JSON is valid YAML. Compose's reset tag is the one YAML-specific value.
    return MARKER + json.dumps(document, indent=2).replace(
        '"profiles": []', '"profiles": !reset []') + '\n'


def generate_override(proxy, endpoint, clients, allowed):
    services = {proxy: {'profiles': [], 'environment': {
        'L2_PROXY_CLIENTS': ','.join(sorted(allowed))}}}
    services.update({name: {'environment': {'L2_PROVIDER': '', 'L2_OXEND': endpoint},
                            'depends_on': {proxy: {'condition': 'service_healthy'}}}
                     for name in clients})
    return dump_override({'services': services})


def setup():
    base = ROOT / 'docker-compose.yml'
    override = ROOT / 'docker-compose.override.yml'
    # Do not replace a user-maintained override or silently ignore a competing file.
    for name in ('compose.yaml', 'compose.yml', 'compose.override.yaml',
                 'compose.override.yml', 'docker-compose.override.yaml'):
        if (ROOT / name).exists():
            raise SetupError(f'{name} conflicts with automatic setup; use the documented docker-compose.yml layout.')
    if os.environ.get('COMPOSE_FILE'):
        raise SetupError('Unset COMPOSE_FILE; this command manages this repository\'s Compose files.')
    if override.exists() and not override.read_text().startswith(MARKER):
        raise SetupError('docker-compose.override.yml is user-managed; it will not be overwritten.')
    current = [base, override] if override.exists() else [base]
    config = json.loads(compose([base], '--profile', '*', 'config', '--format', 'json').stdout)
    services = config['services']
    proxy = 'l2proxy'
    proxy_env = services.get(proxy, {}).get('environment', {})
    if proxy_env.get('ROLE') != 'proxy':
        raise SetupError('The l2proxy service must have ROLE=proxy.')
    network = proxy_env.get('NETWORK', 'mainnet')
    provider = proxy_env.get('L2_PROVIDER', '')
    if not provider or 'YOUR_API_KEY' in provider:
        raise SetupError('Set a real L2_PROVIDER in .env before running setup.')
    clients = sorted(name for name, service in services.items()
                     if name != proxy and service.get('environment', {}).get('ROLE', 'node') == 'node'
                     and service.get('environment', {}).get('NETWORK', 'mainnet') == network)
    if not clients:
        raise SetupError('No nodes on the proxy\'s network were found in docker-compose.yml.')
    port = str(proxy_env.get('QUORUMNET_PORT', '11025' if network == 'stagenet' else '22025'))
    if not port.isdecimal() or not 1 <= int(port) <= 65535:
        raise SetupError('The proxy QUORUMNET_PORT must be a valid port.')
    allowed = set(filter(None, re.split(r'[,\s]+', proxy_env.get('L2_PROXY_CLIENTS') or '')))
    if any(not KEY.fullmatch(key) for key in allowed):
        raise SetupError('Manually configured L2_PROXY_CLIENTS contains an invalid public key.')
    allowed = {key.lower() for key in allowed}

    # Validate the generated YAML/reset syntax before starting any containers.
    with tempfile.TemporaryDirectory(prefix='.l2-setup-', dir=ROOT) as temp:
        # Remove references to services deleted from the base file before even
        # querying Compose; otherwise old overrides can create invalid services.
        if override.exists():
            previous = json.loads(override.read_text()[len(MARKER):].replace(
                '"profiles": !reset []', '"profiles": []'))
            previous['services'] = {name: value for name, value in previous['services'].items()
                                    if name in services}
            filtered = Path(temp) / 'current.yml'
            filtered.write_text(dump_override(previous))
            current = [base, filtered]
        candidate = Path(temp) / 'override.yml'
        candidate.write_text(generate_override(proxy, f'{proxy}:{port}/' + 'a' * 64, clients, allowed))
        compose([base, candidate], '--profile', '*', 'config', '--quiet')
        print(f'Discovering {proxy} and {", ".join(clients)}...', flush=True)
        compose(current, 'up', '-d', '--no-build', '--no-deps', proxy)
        proxy_key = await_key(current, proxy, network)
        bootstrap = Path(temp) / 'bootstrap.json'
        # The temporary file contains a variable reference, never the RPC secret.
        bootstrap.write_text(json.dumps({'services': {name: {'environment': {
            'L2_PROVIDER': '${SESSION_L2_BOOTSTRAP_PROVIDER}', 'L2_OXEND': ''}}
            for name in clients}}))
        bootstrap_env = os.environ | {'SESSION_L2_BOOTSTRAP_PROVIDER': provider}
        for name in clients:
            key = public_key(current, name, network)
            if not key:
                print(f'Starting {name} with temporary direct RPC to discover its identity...', flush=True)
                compose(current + [bootstrap], 'up', '-d', '--no-build', '--no-deps', name,
                        env=bootstrap_env)
                key = await_key(current, name, network)
            allowed.add(key)
        endpoint = f'{proxy}:{port}/{proxy_key}'
        candidate.write_text(generate_override(proxy, endpoint, clients, allowed))
        compose([base, candidate], '--profile', '*', 'config', '--quiet')
        # Replace atomically only after every public key and the final config validate.
        if not override.exists() or override.read_text() != candidate.read_text():
            candidate.chmod(0o600)
            os.replace(candidate, override)
        print('Applying proxy allowlist and node connections...', flush=True)
        compose([base, override], 'up', '-d', '--no-build', '--wait', '--wait-timeout', '180',
                proxy, *clients)
        print(f'Configured {len(clients)} nodes through {endpoint}.')
        print('Saved docker-compose.override.yml; normal docker compose commands load it automatically.')
        print('Health checks passed. Verify L2 synchronization before staking.')


if __name__ == '__main__':
    if len(sys.argv) != 1:
        sys.exit('Usage: python3 configure_l2_proxy.py (configure all nodes on l2proxy\'s network)')
    try:
        with (ROOT / '.l2-setup.lock').open('w') as lock:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
            setup()
    except (SetupError, OSError, ValueError, subprocess.TimeoutExpired) as error:
        sys.exit(f'L2 setup failed: {error}')
