services:
  json-rpc-cache-proxy:
    image: json-rpc-cache-proxy
    ports:
      - "8080:80"
    environment:
      - RPC_ETHEREUM=https://mainnet.infura.io/v3/key
      - WS_ETHEREUM=wss://mainnet.infura.io/ws/v3/key
      - RPC_ARBITRUM=https://arbitrum-mainnet.infura.io/v3/key
      - WS_ARBITRUM=wss://arbitrum-mainnet.infura.io/ws/v3/key
      - RPC_ARBITRUM-SEPOLIA=https://arbitrum-sepolia.infura.io/v3/key
      - WS_ARBITRUM-SEPOLIA=https://arbitrum-sepolia.infura.io/ws/v3/key
      - CACHE_TTL_ETHEREUM=10
      - CACHE_TTL_ARBITRUM=60
      - CACHE_TTL_SOLANA=10
      - CACHE_TTL_ARBITRUM-SEPOLIA=60
    restart: unless-stopped

  oxen00:
    image: registry.schwoi.com/session-node
    ports:
      - "10000:10000"
      - "10001:10001"
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - ./oxen00:/var/lib/oxen
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    environment:
      # SERVICE_NODE_IP_ADDRESS will be auto-detected if not specified
      # - SERVICE_NODE_IP_ADDRESS=x.x.x.x
      - QUORUMNET_PORT=10000
      - P2P_PORT=10001
      - L2_PROVIDER=http://session-node-json-rpc-cache-proxy-1:8080/arbitrum-sepolia
  
  oxen01:
    image: registry.schwoi.com/session-node
    ports:
      - "10010:10010"
      - "10011:10011"
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - ./oxen01:/var/lib/oxen
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    environment:
      # SERVICE_NODE_IP_ADDRESS will be auto-detected if not specified
      # - SERVICE_NODE_IP_ADDRESS=x.x.x.x
      - QUORUMNET_PORT=10010
      - P2P_PORT=10011
      - L2_PROVIDER=http://session-node-json-rpc-cache-proxy-1:8080/arbitrum-sepolia
  
