services:
  oxen00:
    image: registry.schwoi.com/session-node
    ports:
      - "22020:22020/tcp"
      - "22020:22020/udp"
      - "22021:22021/tcp"
      - "22022:22022/tcp"
      - "22025:22025/tcp"
      - "1090:1090/udp"
      - "1190:1190/udp"
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - ./oxen00:/var/lib/oxen
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    environment:
      # SERVICE_NODE_IP_ADDRESS will be auto-detected if not set
      # - SERVICE_NODE_IP_ADDRESS=x.x.x.x
      - QUORUMNET_PORT=22025
      - P2P_PORT=22022
      - L2_PROVIDER=https://arb-mainnet.g.alchemy.com/v2/YOUR_API_KEY

  oxen01:
    image: registry.schwoi.com/session-node
    ports:
      - "22030:22030/tcp"
      - "22030:22030/udp"
      - "22031:22031/tcp"
      - "22032:22032/tcp"
      - "22035:22035/tcp"
      - "1091:1091/udp"
      - "1191:1191/udp"
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - ./oxen01:/var/lib/oxen
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    environment:
      # SERVICE_NODE_IP_ADDRESS will be auto-detected if not set
      # - SERVICE_NODE_IP_ADDRESS=x.x.x.x
      - QUORUMNET_PORT=22035
      - P2P_PORT=22032
      - L2_PROVIDER=https://arb-mainnet.g.alchemy.com/v2/YOUR_API_KEY
