#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
[[ -t 0 ]] || { printf '%sRun this wizard in an interactive terminal.%s\n' "$RED" "$RESET" >&2; exit 1; }
ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
cd -- "$ROOT"
umask 077
STAGING=$(mktemp -d "$ROOT/.node-onboarding.XXXXXXXX")
ENV_FILE="$STAGING/answers.env"
trap 'rm -rf -- "$STAGING"' EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
PYTHON="$ROOT/.onboarding-venv/bin/python"

save_answer() { write_env "$1" "${!1}"; }
backend() { "$PYTHON" "$ROOT/scripts/node_onboarding.py" "$@"; }
ensure_image() {
  if ! docker image inspect "$IMAGE" >/dev/null 2>&1; then
    say "The selected image is not available locally: $IMAGE"
    if confirm 'Pull the selected image from its registry?'; then
      docker pull "$IMAGE"
    else
      warn "Pull or build the selected image locally, then rerun onboarding to continue."
      exit 1
    fi
  fi
}

banner 'Session Node onboarding'

stage 'Prerequisites and node selection'
say 'This configures one node, preserves other services, and can copy an existing identity.'
say 'Nothing starts until you approve it. RPC credentials are entered privately.'
command -v docker >/dev/null || { warn 'Install Docker Engine and Compose first.'; exit 1; }
command -v python3 >/dev/null || { warn 'Install Python 3.9+ and python3-venv first.'; exit 1; }
docker info >/dev/null 2>&1 || { warn 'Docker is unavailable to this user.'; exit 1; }
if [[ ! -x $PYTHON ]] || ! "$PYTHON" -c 'import ruamel.yaml' >/dev/null 2>&1; then
  say 'YAML support will be installed into .onboarding-venv, isolated from system Python.'
  confirm 'Create/update the onboarding environment?' || exit 0
  python3 -m venv "$ROOT/.onboarding-venv"
  "$PYTHON" -m pip install -r "$ROOT/requirements-onboarding.txt"
fi
say 'Existing node services:'
backend list
while true; do
  ask NAME 'Node name to add or edit (lowercase letters, numbers, underscores):'
  [[ -n $NAME ]] || { say 'Cancelled: no node name entered.'; exit 0; }
  if backend defaults --name "$NAME" --answers "$ENV_FILE"; then break; fi
  warn 'Choose another name or correct the reported configuration problem.'
done
EXISTING=$(_existing EXISTING)

stage 'Network, image, and persistent data'
if [[ $EXISTING == yes ]]; then
  NETWORK=$(_existing NETWORK)
  say "Editing $NAME on $NETWORK. Changing networks requires a new service/data directory."
else
  while true; do
    ask NETWORK 'Network (mainnet/stagenet):'
    [[ $NETWORK == mainnet || $NETWORK == stagenet ]] && break
    warn 'Choose mainnet or stagenet.'
  done
  backend defaults --name "$NAME" --network "$NETWORK" --answers "$ENV_FILE"
fi
save_answer NETWORK
say "Current image: $(_existing IMAGE)"
ask IMAGE 'Container image/tag (Enter keeps current):'
save_answer IMAGE
say "Data directory: $(_existing DATA_DIR)"
ask DATA_DIR 'Persistent data directory (Enter keeps current):'
save_answer DATA_DIR

stage 'Public address and ports'
say 'Open/forward these ports on the server firewall. Published and listening ports will match.'
ask PUBLIC_IP 'Public IPv4 (auto for automatic detection):'
[[ $PUBLIC_IP != auto ]] || PUBLIC_IP=''
save_answer PUBLIC_IP
for port_name in P2P_PORT QUORUMNET_PORT; do
  ask "$port_name" "$port_name (current: $(_existing "$port_name")):"
  save_answer "$port_name"
done
if [[ $NETWORK == mainnet ]]; then
  for port_name in STORAGE_LMQ_PORT STORAGE_HTTPS_PORT LOKINET_PORT SESSION_ROUTER_PORT; do
    ask "$port_name" "$port_name (current: $(_existing "$port_name")):"
    save_answer "$port_name"
  done
  [[ -c /dev/net/tun ]] || warn 'The Docker host needs /dev/net/tun before a mainnet node can start.'
fi

stage 'L2 blockchain access'
say 'direct: use your own Arbitrum RPC endpoint.'
say 'proxy: use an existing proxy host, port, and public key.'
say 'local: automatically configure the local l2proxy and participating nodes.'
while true; do
  ask L2_MODE 'L2 access (direct/proxy/local):'
  [[ $L2_MODE == direct || $L2_MODE == proxy || $L2_MODE == local ]] && break
  warn 'Choose direct, proxy, or local.'
done
save_answer L2_MODE
if [[ $L2_MODE == proxy ]]; then
  ask L2_OXEND 'Proxy connection (HOST:PORT/ED25519_PUBLIC_KEY):'
  save_answer L2_OXEND
else
  open_url 'https://docs.getsession.org/contribute-to-the-session-network/running-a-session-node/oxend-l2-tracker-tuning'
  if [[ $NETWORK == mainnet ]]; then
    step 'Copy the Arbitrum One RPC endpoint from your provider account.'
  else
    step 'Copy the Arbitrum Sepolia RPC endpoint from your provider account.'
  fi
  if [[ $L2_MODE == local ]]; then
    say 'The RPC URL will configure l2proxy; this also updates other local proxy users.'
    LOCAL_RPC_URL=$(_existing LOCAL_RPC_URL || true)
    [[ -z $LOCAL_RPC_URL ]] || write_env RPC_URL "$LOCAL_RPC_URL"
  fi
  ask_secret RPC_URL 'RPC provider URL (hidden input):'
  save_answer RPC_URL
fi

stage 'Node identity or migration'
say "keep: retain this node's existing keys, or generate new keys at first startup."
say 'import: copy both key_ed25519 and key_bls from an existing node backup.'
while true; do
  ask KEY_MODE 'Identity (keep/import):'
  [[ $KEY_MODE == keep || $KEY_MODE == import ]] && break
  warn 'Choose keep or import.'
done
save_answer KEY_MODE
if [[ $KEY_MODE == import ]]; then
  warn 'Use keys from the selected network. Never run the old and new nodes with the same identity at once.'
  say 'Copy the key files onto this machine first. Binary and 0x-hex key files are accepted.'
  say 'The originals are preserved. A different identity in the destination will not be overwritten.'
  ask KEY_ED25519 'Path to existing key_ed25519 file:'
  save_answer KEY_ED25519
  ask KEY_BLS 'Path to existing key_bls file:'
  save_answer KEY_BLS
  ensure_image
fi

stage 'Review, save, and optional startup'
say "Node: $NAME ($NETWORK)"
say "Image: $IMAGE"
say "Data: $DATA_DIR"
say "Public IPv4: ${PUBLIC_IP:-automatic}"
say "L2 mode: $L2_MODE; identity: $KEY_MODE"
say "P2P: $P2P_PORT/tcp; Quorumnet: $QUORUMNET_PORT/tcp"
if [[ $NETWORK == mainnet ]]; then
  say "Storage: $STORAGE_LMQ_PORT/tcp+udp, $STORAGE_HTTPS_PORT/tcp; routers: $LOKINET_PORT/udp, $SESSION_ROUTER_PORT/udp"
fi
say 'Provider credentials will be stored in .env and referenced by docker-compose.yml.'
backend validate --answers "$ENV_FILE"
if ! confirm "Save these changes (stopping $NAME first if it is running)?"; then
  say 'Cancelled. Node configuration and keys were not changed.'
  exit 0
fi
write_env STOP_APPROVED yes
backend apply --answers "$ENV_FILE"
if confirm 'Start the configured node now?'; then
  if [[ $KEY_MODE == import ]]; then
    confirm 'Have you stopped the original node using these keys?' || {
      warn 'Saved only. Stop the original node before starting this one.'
      exit 0
    }
  fi
  ensure_image
  if [[ $L2_MODE == local ]]; then
    python3 "$ROOT/configure_l2_proxy.py"
  else
    docker compose up -d --no-build --wait --wait-timeout 180 "$NAME"
  fi
else
  if [[ $L2_MODE == local ]]; then
    note 'Start later with local proxy wiring: python3 configure_l2_proxy.py'
  else
    note "Start later: docker compose up -d --no-build $NAME"
  fi
fi
# Answers are temporary; persistent values were saved by the validated backend.
WRITTEN_ENV=()
finish
say "Saved $NAME. Check docker compose logs $NAME and node status before staking."
