data-dir=$DATA_DIR
log-file=$LOG_FILE
service-node=1
service-node-public-ip=$SERVICE_NODE_IP_ADDRESS
l2-provider=$L2_PROVIDER
quorumnet-port=$QUORUMNET_PORT
p2p-bind-port=$P2P_PORT
#l2-provider=http://backup.example.com
#l2-refresh=60
#l2-timeout=5
#l2-max-logs=1000
#l2-check-interval=170
#l2-check-threshold=120
